const ListProducts = [
  {
    id: 1,
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    category: 'Electronics',
    desc: "Experience the convenience and quality of the Apple Airpods wireless Bluetooth headphones. These headphones provide seamless connectivity to your Apple devices and deliver rich, high-quality audio. The included charging case ensures you never run out of battery, providing multiple charges for extended use. Whether you're listening to music, taking calls, or interacting with Siri, the Apple Airpods offer a premium wireless experience.",
    product_name: 'Apple Airpods',
    price: '$ 129.99',
  },
  {
    id: 2,
    image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    category: 'Clothing',
    desc: "Elevate your casual style with this Men's Classic Cotton T-Shirt. Made from soft and breathable cotton, this t-shirt offers comfort and versatility. Its classic fit and crew neckline make it a wardrobe essential for everyday wear. Available in a variety of colors, this timeless t-shirt pairs effortlessly with jeans, shorts, or casual pants.",
    product_name: 'Classic Cotton T-Shirt',
    price: '$ 19.99',
  },
  {
    id: 3,
    image: 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg',
    category: 'Jewelry',
    desc: 'Add a touch of elegance to your jewelry collection with the Solid Gold Petite Micropave Bracelet. Crafted from genuine 14k gold, this bracelet features delicate micropave detailing that enhances its brilliance. Whether worn alone or layered with other pieces, this timeless bracelet is perfect for any occasion, adding sophistication and charm to your look.',
    product_name: 'Gold Bracelet',
    price: '$ 249.99',
  },
  {
    id: 4,
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    category: 'Electronics',
    desc: 'Stay connected with the Samsung Galaxy S20 Ultra 5G smartphone. Featuring a 6.9-inch Infinity-O display and a powerful camera system, including a 108MP wide lens and 100x Space Zoom, this smartphone captures detailed photos and videos in any environment. With 5G connectivity, you can stream, game, and download at incredible speeds. The Galaxy S20 Ultra 5G is designed to keep up with your busy lifestyle.',
    product_name: 'Samsung Galaxy S20 Ultra',
    price: '$ 1199.99',
  },
  {
    id: 5,
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    category: 'Home & Living',
    desc: 'Upgrade your dining space with the Wooden Dining Chair. Crafted from solid wood, this chair combines classic style with durability. Its ergonomic design and cushioned seat provide comfort during meals and gatherings. Whether used in the dining room, kitchen, or study, this chair adds a touch of elegance and functionality to your home decor.',
    product_name: 'Wooden Dining Chair',
    price: '$ 89.99',
  },
  {
    id: 6,
    image: 'https://fakestoreapi.com/img/61XKvo-nQVL._AC_UX679_.jpg',
    category: 'Home & Living',
    desc: 'Illuminate your space with the Modern Industrial Lamp. Featuring a sleek metal base and adjustable arm, this lamp offers versatile lighting solutions for any room. Its minimalist design complements modern decor, making it ideal for desks, nightstands, or living room tables. Whether used for reading, working, or ambiance, this lamp adds style and functionality to your home or office.',
    product_name: 'Industrial Lamp',
    price: '$ 49.99',
  },
  {
    id: 7,
    image: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg',
    category: 'Electronics',
    desc: "Track your fitness goals and stay connected with the Apple Watch Series 3. Featuring advanced fitness tracking, heart rate monitoring, and GPS, this smartwatch helps you stay active and informed throughout the day. With cellular capabilities, you can make calls, send messages, and stream music directly from your wrist. Whether you're exercising, working, or relaxing, the Apple Watch Series 3 is your ultimate companion.",
    product_name: 'Apple Watch Series 3',
    price: '$ 199.99',
  },
  {
    id: 8,
    image: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
    category: 'Books',
    desc: "Explore the principles of entrepreneurship with 'The Lean Startup' by Eric Ries. This book introduces the Lean Startup methodology, emphasizing continuous innovation, validated learning, and rapid experimentation. Whether you're launching a startup or leading an established company, Ries' insights and practical advice provide actionable strategies for sustainable growth and success.",
    product_name: 'The Lean Startup',
    price: '$ 14.99',
  },
  {
    id: 9,
    image: 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg',
    category: 'Jewelry',
    desc: 'Add a touch of elegance to your ensemble with the Platinum-Plated Sterling Silver Round-Cut Ring. Crafted from premium materials, this ring features a round-cut cubic zirconia stone set in platinum-plated sterling silver. Its timeless design and sparkling brilliance make it a standout accessory for any occasion, adding glamour and sophistication to your look.',
    product_name: 'Platinum-Plated Ring',
    price: '$ 79.99',
  },
  {
    id: 10,
    image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
    category: 'Electronics',
    desc: 'Enhance your productivity with the HP 23.8-inch FHD IPS Monitor. Featuring a Full HD display and ergonomic design, this monitor offers vibrant colors and wide viewing angles. With adjustable tilt and height settings, you can customize your workspace for optimal comfort and efficiency. Whether for work or entertainment, the HP Monitor delivers superior performance and clarity.',
    product_name: 'HP FHD IPS Monitor',
    price: '$ 159.99',
  },
  {
    id: 11,
    image: 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg',
    category: 'Home & Living',
    desc: 'Add a pop of color to your home decor with the Red and White Ceramic Vase. Handcrafted from ceramic, this vase features a modern design and vibrant colors that complement any room. Whether used as a standalone piece or filled with fresh flowers, this vase adds elegance and charm to mantels, shelves, and tabletops. Its versatile style makes it a perfect accent for contemporary interiors.',
    product_name: 'Ceramic Vase',
    price: '$ 29.99',
  },
  {
    id: 12,
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    category: 'Electronics',
    desc: "Capture every moment with the Canon EOS 5D Mark IV DSLR Camera. Featuring a 30.4MP full-frame CMOS sensor and DIGIC 6+ image processor, this camera delivers stunning image quality and performance. Its 61-point AF system and 4K video recording capabilities ensure you never miss a shot. Whether you're a professional photographer or an enthusiast, the EOS 5D Mark IV offers versatility and reliability for all your photography needs.",
    product_name: 'Canon EOS 5D Mark IV',
    price: '$ 2499.99',
  },
  {
    id: 13,
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    category: 'Home & Living',
    desc: 'Transform your dining experience with the Wooden Dining Chair. Crafted from solid wood and upholstered in plush fabric, this chair combines comfort with timeless style. Its ergonomic design and sturdy construction ensure stability and support during meals. Whether used for family dinners or entertaining guests, this dining chair adds elegance and sophistication to any dining space.',
    product_name: 'Wooden Dining Chair',
    price: '$ 99.99',
  },
  {
    id: 14,
    image: 'https://fakestoreapi.com/img/61XKvo-nQVL._AC_UX679_.jpg',
    category: 'Home & Living',
    desc: 'Brighten up your living space with the Modern Industrial Lamp. Featuring a minimalist design and adjustable arm, this lamp offers versatile lighting solutions for any room. Whether placed on a desk, bedside table, or living room shelf, its sleek silhouette enhances your decor while providing functional illumination. Perfect for reading, working, or creating ambiance, this lamp is a stylish addition to modern interiors.',
    product_name: 'Industrial Lamp',
    price: '$ 49.99',
  },
  {
    id: 15,
    image: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg',
    category: 'Electronics',
    desc: "Monitor your health and stay connected with the Apple Watch Series 3. Featuring advanced fitness tracking and heart rate monitoring, this smartwatch helps you achieve your wellness goals. With built-in GPS and cellular capabilities, you can stay connected on the go and stream music directly from your wrist. Whether you're exercising, working, or relaxing, the Apple Watch Series 3 keeps you informed and motivated throughout the day.",
    product_name: 'Apple Watch Series 3',
    price: '$ 199.99',
  },
  {
    id: 16,
    image: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
    category: 'Books',
    desc: "Explore the principles of lean startup methodology with The Lean Startup by Eric Ries. This insightful book offers practical strategies for entrepreneurs to build successful businesses through continuous innovation and customer feedback. Whether you're launching a startup or leading an established company, Ries' approach to lean thinking and rapid experimentation provides actionable insights for sustainable growth and competitive advantage.",
    product_name: 'The Lean Startup',
    price: '$ 14.99',
  },
  {
    id: 17,
    image: 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg',
    category: 'Jewelry',
    desc: "Elevate your jewelry collection with the Women's Platinum-Plated Sterling Silver Round-Cut Ring. Crafted from premium materials, this exquisite ring features a round-cut cubic zirconia stone set in platinum-plated sterling silver. Its timeless design and sparkling brilliance make it a standout accessory for formal occasions or everyday wear. Whether worn alone or paired with other pieces, this ring adds elegance and sophistication to any ensemble.",
    product_name: 'Platinum-Plated Ring',
    price: '$ 79.99',
  },
  {
    id: 18,
    image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
    category: 'Electronics',
    desc: 'Enhance your workspace with the HP 23.8-inch FHD IPS Monitor. Featuring a sleek design and vibrant display, this monitor delivers crisp images and wide viewing angles for an immersive visual experience. With adjustable tilt and height settings, you can customize your viewing preferences for optimal comfort and productivity. Whether used for work or entertainment, the HP Monitor offers superior performance and reliability.',
    product_name: 'HP FHD IPS Monitor',
    price: '$ 159.99',
  },
  {
    id: 19,
    image: 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg',
    category: 'Home & Living',
    desc: 'Bring a touch of artistry to your home decor with the Red and White Ceramic Vase. Handcrafted from high-quality ceramic, this vase features an eye-catching design and vibrant colors that complement any interior style. Whether displayed on its own or filled with fresh flowers, this vase adds elegance and sophistication to mantels, shelves, and tabletops. Its timeless appeal makes it a perfect accent piece for both modern and traditional spaces.',
    product_name: 'Ceramic Vase',
    price: '$ 29.99',
  },
  {
    id: 20,
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    category: 'Electronics',
    desc: 'Experience cutting-edge technology with the Samsung Galaxy S20 Ultra 5G. Featuring a revolutionary camera system with a 108MP wide lens and 100x Space Zoom, this smartphone captures stunning photos and videos in any environment. Its 6.9-inch Infinity-O display delivers immersive visuals, while 5G connectivity ensures fast speeds for streaming and gaming. Whether for work or play, the Galaxy S20 Ultra 5G offers unparalleled performance and versatility.',
    product_name: 'Samsung Galaxy S20 Ultra',
    price: '$ 1199.99',
  },
];

export default ListProducts;
